In [65]:
import pandas as pd

In [66]:
df = pd.read_csv("../data/netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [67]:
df = df.drop_duplicates()

In [68]:
print(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [69]:
df['director'] = df['director'].fillna("Unknown")
df['cast'] = df['cast'].fillna("Unknown")
df['country'] = df['country'].fillna("Unknown")
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [70]:
df['listed_in'] = df['listed_in'].fillna("Unknown").astype(str).apply(lambda x: x.split(', '))

In [71]:
df['country'] = df['country'].fillna("Unknown").astype(str).apply(lambda x: x.split(', '))

In [72]:
print(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [77]:
df.columns = df.columns.str.strip()

if 'rating' in df.columns:
    df['rating'] = df['rating'].fillna(df['rating'].mode()[0])
    df = pd.get_dummies(df, columns=['rating'], prefix='rating')

In [80]:
cols_to_drop = [col for col in df.columns if 'min' in col]
df = df.drop(columns=cols_to_drop)

In [82]:

print("Cleaned and encoded dataset shape:", df_encoded.shape)
print(df_encoded.head())

Cleaned and encoded dataset shape: (8807, 1288)
  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water    Rajiv Chilaka
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans    Rajiv Chilaka
4      s5  TV Show           Kota Factory    Rajiv Chilaka

                                                cast          date_added  \
0                                 David Attenborough  September 25, 2021
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...  September 24, 2021
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...  September 24, 2021
3                                 David Attenborough  September 24, 2021
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...  September 24, 2021

   release_year   duration                                        description  \
0          2020     90 min  As her father nears the end of his life, filmm...
1          2021  2 Seasons  After crossing paths at a party, a Cape Town t...
2          2021   1 Season  To protect his family from a powerful drug lor...
3          2021   1 Season  Feuds, flirtations and toilet talk go down amo...
4          2021  2 Seasons  In a city of coaching centers known to train I...

   listed_in_Action & Adventure  ...  \
0                         False  ...
1                         False  ...
2                         False  ...
3                         False  ...
4                         False  ...

   country_Uruguay, Argentina, Germany, Spain  \
0                                       False
1                                       False
2                                       False
3                                       False
4                                       False

   country_Uruguay, Argentina, Spain  country_Uruguay, Germany  \
0                              False                     False
1                              False                     False
2                              False                     False
3                              False                     False
4                              False                     False

   country_Uruguay, Guatemala  country_Uruguay, Spain, Mexico  \
0                       False                           False
1                       False                           False
2                       False                           False
3                       False                           False
4                       False                           False

   country_Venezuela  country_Venezuela, Colombia  country_Vietnam  \
0              False                        False            False
1              False                        False            False
2              False                        False            False
3              False                        False            False
4              False                        False            False

   country_West Germany  country_Zimbabwe
0                 False             False
1                 False             False
2                 False             False
3                 False             False
4                 False             False

[5 rows x 1288 columns]

In [84]:
df.columns = df.columns.str.strip().str.lower()

In [85]:
df.shape

(8807, 25)

In [86]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,listed_in,...,rating_pg-13,rating_r,rating_tv-14,rating_tv-g,rating_tv-ma,rating_tv-pg,rating_tv-y,rating_tv-y7,rating_tv-y7-fv,rating_ur
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,[United States],"September 25, 2021",2020,90 min,[Documentaries],...,True,False,False,False,False,False,False,False,False,False
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",[South Africa],"September 24, 2021",2021,2 Seasons,"[International TV Shows, TV Dramas, TV Mysteries]",...,False,False,False,False,True,False,False,False,False,False
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",[Unknown],"September 24, 2021",2021,1 Season,"[Crime TV Shows, International TV Shows, TV Ac...",...,False,False,False,False,True,False,False,False,False,False
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,[Unknown],"September 24, 2021",2021,1 Season,"[Docuseries, Reality TV]",...,False,False,False,False,True,False,False,False,False,False
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",[India],"September 24, 2021",2021,2 Seasons,"[International TV Shows, Romantic TV Shows, TV...",...,False,False,False,False,True,False,False,False,False,False

In [87]:
df.to_csv("../data/netflix_cleaned.csv", index=False)